### ISSUE TITLE
Random 3

### ISSUE THREAD

**Issue by kevadamson** [bymayo/dribbble#2]
Any idea the tags for pulling 3 random shots?

**Comment by bymayo** [comment]
@kevadamson From the authenticated user? Or from the *whole* of Dribbble?

**Comment by kevadamson** [comment]
User.

Not sure this is the best way, but ended up doing it like this:

```
{% set shots = craft.dribbble.get('user/shots', 999) %}
{% set shots = shuffle(shots) %}
{% for shot in shots|slice(0,3) %}
...
{% endfor %}
```

**Comment by bymayo** [comment]
Yeah I think your better reducing that limit though as your request might be a bit large! Considering you only want 3 shots.

But thats the way I would do it. I checked the Dribbble API and theres no parameters you can pass, to get a random order, or any order for that fact.
